<a href="https://colab.research.google.com/github/PreethiV-del/PPDA/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating a 1D NumPy array
data1 = [6, 7, 5, 8, 0, 1]   #it is a list
arr1 = np.array(data1)       # list --> converts to ndarray

print(arr1) # [6 7 5 8 0 1]
print("Type:",type(arr1))     # Type: <class 'numpy.ndarray'>
print("Shape:", arr1.shape)    # Shape: (6,)
print("Size:",arr1.size)       # Size: 6
print("Dimensions:", arr1.ndim)     # Dimensions: 1
print("Data type:", arr1.dtype)     # Data type: int64
print("Item_Size:",arr1.itemsize)       # size in bytes of each element of the array.
print("total_memory: =", arr1.size * arr1.itemsize,"bytes")

[6 7 5 8 0 1]
Type: <class 'numpy.ndarray'>
Shape: (6,)
Size: 6
Dimensions: 1
Data type: int64
Item_Size: 8
total_memory: = 48 bytes


In [ ]:
import numpy as np

# Creating a 2D NumPy array from a list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print("Dimensions:", arr2.ndim)   # Output: 2
print("Shape:", arr2.shape)       # Output: (2,4)
print(arr2[1])                    # [5,6,7,8]

Dimensions: 2
Shape: (2, 4)
[5 6 7 8]


In [ ]:
import numpy as np

# 1D array
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 2D array
d2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# 3D array
d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Shape of 1D array:", d1.shape)
print("Shape of 2D array:", d2.shape)
print("Shape of 3D array:", d3.shape)

Shape of 1D array: (12,)
Shape of 2D array: (4, 3)
Shape of 3D array: (2, 2, 3)


In [4]:
import numpy as np

array1 = np.array([[0, 1, 2], [2, 3, 4]]) # Manual creation
array2 = np.array( [ [1,2], [3,4] ], dtype=float) # Specifying data type
array3 = np.zeros((2, 3)) # Array of zeros
array4 = np.ones((2, 3)) # Array of ones
array5 = np.eye(3) # Identity matrix
array6 = np.arange(0, 10, 2) # Sequence from 0 to 8 with step 2
array7 = np.linspace(0, 10, 5) # create 5 elements in between 0 to 10 with equal space
array8 = np.random.randint(0, 10, (3, 3)) # Random integers in a 3x3 array

print(array1, "\n")
print(array2, "\n")
print(array3, "\n")
print(array4, "\n")
print(array5, "\n")
print(array6, "\n")
print(array7, "\n")
print(array8, "\n")

[[0 1 2]
 [2 3 4]] 

[[1. 2.]
 [3. 4.]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[0 2 4 6 8] 

[ 0.   2.5  5.   7.5 10. ] 

[[5 7 2]
 [9 9 2]
 [3 8 1]] 



In [5]:
import numpy as np

arr = np.arange(10)
print("Original array:", arr) # Original array: [0 1 2 3 4 5 6 7 8 9]
print("Element at index 5:", arr[5]) # Element at index 5: 5
print("Slice from index 5 to 8:", arr[5:8]) # Slice from index 5 to 8: [5 6 7]

arr[5:8] = 12
print("Modified array:", arr) # Modified array: [ 0 1 2 3 4 12 12 12 8 9]

# Try 2-D
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Original array:", arr_2d)
print("Original array:", arr_2d.ndim)
print("Element at index 0:", arr_2d[0])
print("Slice from index at 0 form 1 to 3:", arr_2d[0,1:3])
arr_2d[1, 1] = 12
print("Modified array:", arr_2d)

Original array: [0 1 2 3 4 5 6 7 8 9]
Element at index 5: 5
Slice from index 5 to 8: [5 6 7]
Modified array: [ 0  1  2  3  4 12 12 12  8  9]
Original array: [[1 2 3]
 [4 5 6]]
Original array: 2
Element at index 0: [1 2 3]
Slice from index at 0 form 1 to 3: [2 3]
Modified array: [[ 1  2  3]
 [ 4 12  6]]


In [6]:
# Create a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print("Original Array:\n", arr)

# Slice the first row
row_slice = arr[0, :] # Equivalent to arr[0]

# Slice the second column
col_slice = arr[:, 1]

# Slice a submatrix (rows 1-2, columns 2-3)
submatrix = arr[1:3, 2:4]

print("\nFirst Row:", row_slice)
print("Second Column:", col_slice)
print("Submatrix:\n", submatrix)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row: [1 2 3 4]
Second Column: [ 2  6 10]
Submatrix:
 [[ 7  8]
 [11 12]]


In [7]:
import numpy as np

arr_3 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [1., 3., 5.]])
arr_tranp = arr_3.transpose()

print("Original matrix:\n", arr_3)
print("Transpose matrix:\n", arr_tranp)

# Try:
arr_3.shape
arr_3.T
arr_3.T.shape

Original matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 3. 5.]]
Transpose matrix:
 [[1. 4. 7. 1.]
 [2. 5. 8. 3.]
 [3. 6. 9. 5.]]


(3, 4)

In [8]:
arr = np.array([5, 2, 8, 1, 3])
arr2D = np.array([[3, 2, 1], [6, 5, 4]])
# Sorting in ascending order (default)
sorted_arr = np.sort(arr)
print(sorted_arr) # Output: [1 2 3 5 8]
# Sorting in descending order
sorted_desc = np.sort(arr)[::-1]
print(sorted_desc) # Output: [8 5 3 2 1]
# Sort each row
sorted_rows = np.sort(arr2D, axis=0) # [[1 2 3]
print(sorted_rows) # [4 5 6]]
# Sort each row # Output:
sorted_cols = np.sort(arr2D, axis=1) # [[3 2 1]
print(sorted_cols) # [6 5 4]]

[1 2 3 5 8]
[8 5 3 2 1]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.arange(26)

reshaped_arr = arr.reshape(4, 2)
print("Original Array (1D):\n", arr)
print("Reshaped Array (4x2):\n", reshaped_arr)

reshaped_arr_3D = arr.reshape(2, 7, 8)
print("Reshaped Array (7x8x9):\n", reshaped_arr_3D)

ValueError: cannot reshape array of size 26 into shape (4,2)

In [17]:
import numpy as np

arr = np.arange(26)

reshaped_arr = arr.reshape(2, 13)
print("Original Array (1D):\n", arr)
print("Reshaped Array (2x13):\n", reshaped_arr)


reshaped_arr_3D = arr.reshape(2, 1, -1)
print("Reshaped Array (2, 1, 13):\n", reshaped_arr_3D)

Original Array (1D):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
Reshaped Array (2x13):
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]
Reshaped Array (2, 1, 13):
 [[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]]

 [[13 14 15 16 17 18 19 20 21 22 23 24 25]]]
